version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "15672:15672"

  postgres:
    image: postgres:11.3
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: /bin/bash ./commands/wsgi/${SERVER}.sh
    container_name: api
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/srv/project
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres

  celery:
    build: .
    command: /bin/bash ./commands/start_celery.sh
    container_name: celery
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/srv/project
    depends_on:
      - rabbitmq
      - postgres

  celerybeat:
    build: .
    command: /bin/bash ./commands/start_celerybeat.sh
    container_name: celerybeat
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/srv/project
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata:
