# Generated by Django 2.2.10 on 2020-05-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0002_auto_20200529_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
